import JsonDB from "./Database/JsonDB";
import Server from "./Server/server";
import simple from "./Server/simple";
import Router from "./Middleware/router";
import SubDomain from "./Middleware/subdomain";
import StaticDir from "./Middleware/staticdir";
import app from "./application";
export { JsonDB, Server, Router, SubDomain, StaticDir, simple };
export * from "./declarations";
export default app;
